# Transcribed from drugtrace_data Sheet2. (reagent, substance, firstName, firstHex,
# finalName, finalHex, time, notes, org, doc, page, year, status)
ROWS = [
("Marquis","Amphetamine","Orange","#FFA500","Dark Brown","#654321","0-5s","Reddish-orange transition","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Methamphetamine","Orange","#FFA500","Dark Brown","#654321","0-5s","Deep reddish-orange","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","MDMA","Dark Purple","#300030","Black","#000000","0-5s","Rapid color development","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Morphine","Purple","#800080","Dark Violet","#420039","0-10s","Opiate class reaction","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Heroin","Purple","#800080","Dark Violet","#420039","0-10s","Diacetylmorphine reaction","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Codeine","Purple","#800080","Dark Violet","#420039","0-10s","Opiate class reaction","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Cocaine","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Does not react with Marquis","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Scott (Cobalt Thiocyanate)","Cocaine HCl","Pink","#FFC0CB","Dark Blue","#00008B","Immediate","Precipitate forms in Step 1","NIJ","Color Test Reagents/Kits for Preliminary Identification",8,2000,"Verified"),
("Duquenois-Levine","Cannabis / THC","Clear","#FFFFFF","Purple / Violet","#8A2BE2","1-2 min","Purple transfers to organic layer","UNODC","Rapid Testing Methods for Drugs of Abuse",14,1998,"Verified"),
("Mecke","Heroin","Deep Green","#006400","Dark Blue-Green","#004040","0-5s","Distinct from Marquis reaction","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Ehrlich (Van Urk)","LSD","Grey","#808080","Deep Purple","#360033","1-3 min","Indole ring reaction","UNODC","Rapid Testing Methods for Drugs of Abuse",15,1998,"Verified"),
("Simon's","Methamphetamine","Clear","#FFFFFF","Deep Blue","#00008B","0-10s","Secondary amine specific","NIJ","Color Test Reagents/Kits for Preliminary Identification",14,2000,"Verified"),
("Simon's","Amphetamine","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Primary amine (does not react)","NIJ","Color Test Reagents/Kits for Preliminary Identification",14,2000,"Verified"),
("Dille-Koppanyi","Phenobarbital","Pale Pink","#FADADD","Violet / Purple","#8A2BE2","Immediate","Barbiturate class test","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Marquis","Tramadol","Unconfirmed","#D3D3D3","Unconfirmed","#D3D3D3","Unconfirmed","Not listed in standard UNODC/NIJ kit manuals",None,None,None,None,"Unconfirmed"),
("Marquis","Fentanyl","Unconfirmed","#D3D3D3","Unconfirmed","#D3D3D3","Unconfirmed","Standard color kits lack reliable screening",None,None,None,None,"Unconfirmed"),
("Zimmermann","Diazepam","Unconfirmed","#D3D3D3","Unconfirmed","#D3D3D3","Unconfirmed","Variable in standard field kit tables",None,None,None,None,"Unconfirmed"),
("Marquis","Aspirin (Acetylsalicylic Acid)","Clear","#FFFFFF","Pink / Red","#FF0000","0-10s","Slowly turns deep red / cherry red","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Paracetamol (Acetaminophen)","Clear","#FFFFFF","Pale Pink","#FFD1DC","10-30s","Very mild or delayed color shift","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Caffeine","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Inert to Marquis test","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Levamisole","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Does not react with Marquis","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Procaine","Clear","#FFFFFF","Pale Yellow","#FFFACD","0-10s","Light yellow shift","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Lidocaine","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Inert to Marquis test","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Quinine","Clear","#FFFFFF","Pale Yellow","#FFFACD","0-10s","Light yellow development","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Lactose / Glucose","Clear","#FFFFFF","Brown","#A52A2A","> 30s","Slow charring / caramelization by H2SO4","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Scott (Cobalt Thiocyanate)","Lidocaine","Pink","#FFC0CB","Dark Blue","#00008B","Immediate","False positive for Cocaine in Step 1","NIJ","Color Test Reagents/Kits for Preliminary Identification",8,2000,"Verified"),
("Scott (Cobalt Thiocyanate)","Procaine","Pink","#FFC0CB","Dark Blue","#00008B","Immediate","False positive for Cocaine in Step 1","NIJ","Color Test Reagents/Kits for Preliminary Identification",8,2000,"Verified"),
("Liebermann","Acetaminophen","Clear","#FFFFFF","Dark Violet","#420039","0-5s","Strong reaction; can mask active drug","NIJ","Color Test Reagents/Kits for Preliminary Identification",12,2000,"Verified"),
("Marquis","Phenacetin","Clear","#FFFFFF","Dark Violet","#420039","0-10s","Strong color transition","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Marquis","Boric Acid / Starch","No Reaction","#E0E0E0","No Reaction","#E0E0E0","N/A","Inert filler material","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Mephedrone (4-MMC)","Clear","#FFFFFF","Bright Yellow","#FFFF00","0-10s","Synthetic cathinone screening","UNODC","Recommended Methods for Identification of Synthetic Cathinones",18,2012,"Verified"),
("Liebermann","Mephedrone (4-MMC)","Clear","#FFFFFF","Orange / Red","#FF4500","0-5s","Strong color shift for cathinones","UNODC","Recommended Methods for Identification of Synthetic Cathinones",18,2012,"Verified"),
("Marquis","MDPV","Clear","#FFFFFF","Yellowish Brown","#967969","0-10s","Substituted cathinone reaction","UNODC","Recommended Methods for Identification of Synthetic Cathinones",19,2012,"Verified"),
("Marquis","alpha-PVP (Flakka)","Clear","#FFFFFF","Pale Yellow","#FFFACD","0-10s","Cathinone class reaction","UNODC","Recommended Methods for Identification of Synthetic Cathinones",19,2012,"Verified"),
("Froehde","Morphine","Clear","#FFFFFF","Purple-Violet","#8A2BE2","0-5s","Turns dark green over time","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Froehde","MDMA","Clear","#FFFFFF","Black / Blue","#0A1172","0-5s","Rapid dark color change","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Chen's","Ephedrine","Clear","#FFFFFF","Purple / Violet","#8A2BE2","Immediate","Copper complex formation for ephedrine","NIJ","Color Test Reagents/Kits for Preliminary Identification",13,2000,"Verified"),
("Mandelin","Ketamine","Clear","#FFFFFF","Orange / Brown","#CC5500","0-10s","Dissociative screening test","NIJ","Color Test Reagents/Kits for Preliminary Identification",12,2000,"Verified"),
("Marquis","2C-B","Clear","#FFFFFF","Yellow to Green","#9ACD32","0-10s","Phenethylamine derivative test","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Morris","Ketamine","Clear","#FFFFFF","Violet / Purple","#8A2BE2","Immediate","Specific test for Ketamine HCl","NIJ","Color Test Reagents/Kits for Preliminary Identification",12,2000,"Verified"),
("Liebermann","Methadone","Clear","#FFFFFF","Orange / Brown","#CC5500","0-10s","Opioid class test","NIJ","Color Test Reagents/Kits for Preliminary Identification",12,2000,"Verified"),
("Zwikker","Pentobarbital","Clear","#FFFFFF","Purple-Violet","#8A2BE2","Immediate","Barbiturate screening reagent","NIJ","Color Test Reagents/Kits for Preliminary Identification",13,2000,"Verified"),
("Fast Blue B","THC / Cannabis","Clear","#FFFFFF","Red / Dark Violet","#800020","1-2 min","Specific dye test for cannabinoids","UNODC","Rapid Testing Methods for Drugs of Abuse",14,1998,"Verified"),
("Nitric Acid","Morphine","Clear","#FFFFFF","Crimson Red","#DC143C","0-5s","Distinguishes Morphine from Heroin","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Nitric Acid","Codeine","Clear","#FFFFFF","Yellow","#FFFF00","0-5s","Slow yellow transition","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Robadope","Amphetamine","Clear","#FFFFFF","Red / Violet","#C71585","0-10s","Specific for primary amines","NIJ","Color Test Reagents/Kits for Preliminary Identification",14,2000,"Verified"),
("Mecke","Heroin","Clear","#FFFFFF","Deep Green","#006400","0-5s","Diacetylmorphine reaction","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Mecke","Psilocybin","Clear","#FFFFFF","Greenish Blue","#008080","0-10s","Tryptamine derivative test","UNODC","Rapid Testing Methods for Drugs of Abuse",15,1998,"Verified"),
("Ehrlich (Van Urk)","Psilocin / Psilocybin","Clear","#FFFFFF","Purple-Violet","#8A2BE2","1-3 min","Indole nucleus detection","UNODC","Rapid Testing Methods for Drugs of Abuse",15,1998,"Verified"),
("Zimmermann","Diazepam","Clear","#FFFFFF","Pinkish Purple","#D87093","1-2 min","Benzodiazepine class test","UNODC","Rapid Testing Methods for Drugs of Abuse",16,1998,"Verified"),
("Duquenois-Levine","CBD (Cannabidiol)","Clear","#FFFFFF","Violet / Blue","#8A2BE2","1-2 min","Extracts into chloroform layer","UNODC","Rapid Testing Methods for Drugs of Abuse",10,1998,"Verified"),
("Scott (Cobalt Thiocyanate)","Cocaine HCl","Clear","#FFFFFF","Blue (Precipitate)","#0000FF","0-5s","Three-step cobalt thiocyanate test","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Scott (Cobalt Thiocyanate)","Cocaine Base (Crack)","Clear","#FFFFFF","Blue (Soluble in Chloroform)","#0000FF","0-5s","Distinguishes salt from base with HCl addition","NIJ","Color Test Reagents/Kits for Preliminary Identification",10,2000,"Verified"),
("Simon's","MDMA","Clear","#FFFFFF","Deep Blue","#00008B","0-5s","Specific test for secondary amines","NIJ","Color Test Reagents/Kits for Preliminary Identification",14,2000,"Verified"),
("Simon's","Amphetamine","Clear","#FFFFFF","No Reaction (Clear)","#FFFFFF","0-10s","Negative result differentiates primary from secondary amine","NIJ","Color Test Reagents/Kits for Preliminary Identification",14,2000,"Verified"),
("Dille-Koppanyi","Secobarbital","Clear","#FFFFFF","Purple-Violet","#8A2BE2","Immediate","Barbiturate ring detection reagent","NIJ","Color Test Reagents/Kits for Preliminary Identification",13,2000,"Verified"),
("Dille-Koppanyi","Phenobarbital","Clear","#FFFFFF","Purple-Violet","#8A2BE2","Immediate","Barbiturate class test","NIJ","Color Test Reagents/Kits for Preliminary Identification",13,2000,"Verified"),
("Ehrlich (Van Urk)","DMT","Clear","#FFFFFF","Purple-Violet","#8A2BE2","1-3 min","Tryptamine class detection","UNODC","Rapid Testing Methods for Drugs of Abuse",15,1998,"Verified"),
("FPN","Chlorpromazine","Clear","#FFFFFF","Orange-Red","#FF4500","0-10s","Phenothiazine detection reagent","NIJ","Color Test Reagents/Kits for Preliminary Identification",15,2000,"Verified"),
("GHB Reagent","GHB (Gamma-Hydroxybutyrate)","Clear","#FFFFFF","Green / Brown","#556B2F","0-10s","Chromium trioxide oxidation test","NIJ","Color Test Reagents/Kits for Preliminary Identification",16,2000,"Verified"),
("Ferric Chloride","Aspirin (Salicylates)","Clear","#FFFFFF","Violet / Purple","#8A2BE2","Immediate","Detects phenolic groups and salicylic acid derivatives","NIJ","Color Test Reagents/Kits for Preliminary Identification",16,2000,"Verified"),
("Mandelin","PMA (Paramethoxyamphetamine)","Clear","#FFFFFF","Reddish Brown","#8B0000","0-10s","Phenethylamine toxic derivative test","UNODC","Rapid Testing Methods for Drugs of Abuse",13,1998,"Verified"),
("Mandelin","Methadone","Clear","#FFFFFF","Dark Blue / Green","#004040","0-10s","Synthetic opioid screening","NIJ","Color Test Reagents/Kits for Preliminary Identification",12,2000,"Verified"),
("Mecke","Mescaline","Clear","#FFFFFF","Orange-Brown","#CC5500","0-10s","Psychedelic phenethylamine test","UNODC","Rapid Testing Methods for Drugs of Abuse",14,1998,"Verified"),
("Dragendorff","General Alkaloids","Clear","#FFFFFF","Orange-Red Precipitate","#FF4500","Immediate","General alkaloid screening test","UNODC","Rapid Testing Methods for Drugs of Abuse",8,1998,"Verified"),
("Mayer's","General Alkaloids","Clear","#FFFFFF","White/Cream Precipitate","#FFFDD0","Immediate","Precipitation test for tertiary amines","UNODC","Rapid Testing Methods for Drugs of Abuse",8,1998,"Verified"),
("Marquis","Fentanyl","Clear","#FFFFFF","No Reaction / Faint Orange","#FFE5B4","0-10s","Fentanyl screening requires immunoassay or Mandelin","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","5-MeO-DMT","Clear","#FFFFFF","Yellow to Black","#000000","0-5s","Tryptamine ring reaction","UNODC","Rapid Testing Methods for Drugs of Abuse",15,1998,"Verified"),
("Marquis","2C-I","Clear","#FFFFFF","Yellow to Black","#000000","0-10s","Substituted phenethylamine","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","2C-E","Clear","#FFFFFF","Yellowish Green","#9ACD32","0-10s","Halogenated phenethylamine","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","DOC","Clear","#FFFFFF","Green to Dark Blue","#00008B","0-10s","Substituted amphetamine","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","DOI","Clear","#FFFFFF","Yellowish Green","#9ACD32","0-10s","Substituted amphetamine","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","4-FA","Clear","#FFFFFF","No Reaction / Faint Pink","#FFC0CB","0-10s","Fluoroamphetamine test","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Marquis","Synthetic Cannabinoids (JWH-018)","Clear","#FFFFFF","Yellow to Brown","#A52A2A","0-10s","NPS synthetic cannabinoid","UNODC","Rapid Testing Methods for Drugs of Abuse",10,1998,"Verified"),
("Fast Blue BB","THC / Cannabis","Clear","#FFFFFF","Reddish Violet","#C71585","1-2 min","Azo coupling cannabinoid","UNODC","Rapid Testing Methods for Drugs of Abuse",14,1998,"Verified"),
("Liebermann","MDMA","Clear","#FFFFFF","Black","#000000","0-5s","Secondary amine oxidation","UNODC","Rapid Testing Methods for Drugs of Abuse",12,1998,"Verified"),
("Liebermann","Amphetamine","Clear","#FFFFFF","Red-Orange","#FF4500","0-5s","Primary amine reaction","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Liebermann","Methamphetamine","Clear","#FFFFFF","Red-Orange","#FF4500","0-5s","Secondary amine reaction","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Liebermann","Heroin","Clear","#FFFFFF","Black","#000000","0-5s","Diacetylmorphine test","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
("Liebermann","Codeine","Clear","#FFFFFF","Black","#000000","0-5s","Opiate oxidation","NIJ","Color Test Reagents/Kits for Preliminary Identification",11,2000,"Verified"),
]
